export const activationBridgeFlags = {
  activationBridgeEnabled: true,
  activationContractDraftBuilderEnabled: true,
  activationPreconditionChecklistEnabled: true,
  activationBridgeSafetyEngineEnabled: true,
  activationBridgeGateEngineEnabled: true,
  activationBridgeDiagnosticsEnabled: true,
  activationBridgeExplanationEnabled: true,
  activationBridgeUiEnabled: true,

  activationBridgeControlsRealActivation: false as const,
  activationBridgeControlsApplyPlanning: false as const,
  activationBridgeControlsCreateSessions: false as const,
  activationBridgeControlsStartSessions: false as const,
  activationBridgeControlsBlocking: false as const,
  activationBridgeControlsTaskCompletion: false as const,
  activationBridgeControlsPersistContract: false as const,
  activationBridgeControlsPersistReview: false as const,
  activationBridgeControlsLocalStorage: false as const,
  activationBridgeControlsStoreWrites: false as const,
  activationBridgeControlsAutoExecute: false as const,
  activationBridgeControlsIpc: false as const,
  activationBridgeControlsElectronMain: false as const,
}
